# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@apollo/client-3.4.11" = {
      name = "_at_apollo_slash_client";
      packageName = "@apollo/client";
      version = "3.4.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@apollo/client/-/client-3.4.11.tgz";
        sha512 = "+A0z/Vy7sDg1uyijv3t9w1U0ybxn0bSpMUZHpsb2cLg/zM8fEHQ217226buzJ+cPUA1GVfJ8n6JsiN26RchvNA==";
      };
    };
    "@apollo/protobufjs-1.2.2" = {
      name = "_at_apollo_slash_protobufjs";
      packageName = "@apollo/protobufjs";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@apollo/protobufjs/-/protobufjs-1.2.2.tgz";
        sha512 = "vF+zxhPiLtkwxONs6YanSt1EpwpGilThpneExUN5K3tCymuxNnVq2yojTvnpRjv2QfsEIt/n7ozPIIzBLwGIDQ==";
      };
    };
    "@apollographql/apollo-tools-0.5.1" = {
      name = "_at_apollographql_slash_apollo-tools";
      packageName = "@apollographql/apollo-tools";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@apollographql/apollo-tools/-/apollo-tools-0.5.1.tgz";
        sha512 = "ZII+/xUFfb9ezDU2gad114+zScxVFMVlZ91f8fGApMzlS1kkqoyLnC4AJaQ1Ya/X+b63I20B4Gd+eCL8QuB4sA==";
      };
    };
    "@apollographql/graphql-playground-html-1.6.27" = {
      name = "_at_apollographql_slash_graphql-playground-html";
      packageName = "@apollographql/graphql-playground-html";
      version = "1.6.27";
      src = fetchurl {
        url = "https://registry.npmjs.org/@apollographql/graphql-playground-html/-/graphql-playground-html-1.6.27.tgz";
        sha512 = "tea2LweZvn6y6xFV11K0KC8ETjmm52mQrW+ezgB2O/aTQf8JGyFmMcRPFgUaQZeHbWdm8iisDC6EjOKsXu0nfw==";
      };
    };
    "@apollographql/graphql-upload-8-fork-8.1.3" = {
      name = "_at_apollographql_slash_graphql-upload-8-fork";
      packageName = "@apollographql/graphql-upload-8-fork";
      version = "8.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@apollographql/graphql-upload-8-fork/-/graphql-upload-8-fork-8.1.3.tgz";
        sha512 = "ssOPUT7euLqDXcdVv3Qs4LoL4BPtfermW1IOouaqEmj36TpHYDmYDIbKoSQxikd9vtMumFnP87OybH7sC9fJ6g==";
      };
    };
    "@babel/runtime-7.15.3" = {
      name = "_at_babel_slash_runtime";
      packageName = "@babel/runtime";
      version = "7.15.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/runtime/-/runtime-7.15.3.tgz";
        sha512 = "OvwMLqNXkCXSz1kSm58sEsNuhqOx/fKpnUnKnFB5v8uDda5bLNEHNgKPvhDN6IU0LDcnHQ90LlJ0Q6jnyBSIBA==";
      };
    };
    "@graphql-tools/merge-8.1.2" = {
      name = "_at_graphql-tools_slash_merge";
      packageName = "@graphql-tools/merge";
      version = "8.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@graphql-tools/merge/-/merge-8.1.2.tgz";
        sha512 = "kFLd4kKNJXYXnKIhM8q9zgGAtbLmsy3WmGdDxYq3YHBJUogucAxnivQYyRIseUq37KGmSAIWu3pBQ23TKGsGOw==";
      };
    };
    "@graphql-tools/schema-8.2.0" = {
      name = "_at_graphql-tools_slash_schema";
      packageName = "@graphql-tools/schema";
      version = "8.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@graphql-tools/schema/-/schema-8.2.0.tgz";
        sha512 = "ufmI5mJQa8NJczzfkh0pUttKvspqDcT5LLakA3jUmOrrE4d4NVj6onZlazdTzF5sAepSNqanFnwhrxZpCAJMKg==";
      };
    };
    "@graphql-tools/utils-8.2.2" = {
      name = "_at_graphql-tools_slash_utils";
      packageName = "@graphql-tools/utils";
      version = "8.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@graphql-tools/utils/-/utils-8.2.2.tgz";
        sha512 = "29FFY5U4lpXuBiW9dRvuWnBVwGhWbGLa2leZcAMU/Pz47Cr/QLZGVgpLBV9rt+Gbs7wyIJM7t7EuksPs0RDm3g==";
      };
    };
    "@graphql-typed-document-node/core-3.1.0" = {
      name = "_at_graphql-typed-document-node_slash_core";
      packageName = "@graphql-typed-document-node/core";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@graphql-typed-document-node/core/-/core-3.1.0.tgz";
        sha512 = "wYn6r8zVZyQJ6rQaALBEln5B1pzxb9shV5Ef97kTvn6yVGrqyXVnDqnU24MXnFubR+rZjBY9NWuxX3FB2sTsjg==";
      };
    };
    "@josephg/resolvable-1.0.1" = {
      name = "_at_josephg_slash_resolvable";
      packageName = "@josephg/resolvable";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@josephg/resolvable/-/resolvable-1.0.1.tgz";
        sha512 = "CtzORUwWTTOTqfVtHaKRJ0I1kNQd1bpn3sUh8I3nJDVY+5/M/Oe1DnEWzPQvqq/xPIIkzzzIP7mfCoAjFRvDhg==";
      };
    };
    "@prisma/client-3.2.0" = {
      name = "_at_prisma_slash_client";
      packageName = "@prisma/client";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@prisma/client/-/client-3.2.0.tgz";
        sha512 = "YCS/N3DZWoaKXhyS8dHwgUvT/NKXvlLbB5fsy0FvYC305JgNtMLjNbxsx0HjIcNw82MEhP7zWEXNvOLpOgGCUg==";
      };
    };
    "@prisma/engines-version-3.2.0-34.afdab2f10860244038c4e32458134112852d4dad" = {
      name = "_at_prisma_slash_engines-version";
      packageName = "@prisma/engines-version";
      version = "3.2.0-34.afdab2f10860244038c4e32458134112852d4dad";
      src = fetchurl {
        url = "https://registry.npmjs.org/@prisma/engines-version/-/engines-version-3.2.0-34.afdab2f10860244038c4e32458134112852d4dad.tgz";
        sha512 = "zYzFOmFvk5YzShqm6DuK7ULtjbJQpebAeD3gcpPfPjx6Uf9pug3bxeswp8/3sk2KKVUeKPUQg5p3TZLskyBNjA==";
      };
    };
    "@protobufjs/aspromise-1.1.2" = {
      name = "_at_protobufjs_slash_aspromise";
      packageName = "@protobufjs/aspromise";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/aspromise/-/aspromise-1.1.2.tgz";
        sha1 = "9b8b0cc663d669a7d8f6f5d0893a14d348f30fbf";
      };
    };
    "@protobufjs/base64-1.1.2" = {
      name = "_at_protobufjs_slash_base64";
      packageName = "@protobufjs/base64";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/base64/-/base64-1.1.2.tgz";
        sha512 = "AZkcAA5vnN/v4PDqKyMR5lx7hZttPDgClv83E//FMNhR2TMcLUhfRUBHCmSl0oi9zMgDDqRUJkSxO3wm85+XLg==";
      };
    };
    "@protobufjs/codegen-2.0.4" = {
      name = "_at_protobufjs_slash_codegen";
      packageName = "@protobufjs/codegen";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/codegen/-/codegen-2.0.4.tgz";
        sha512 = "YyFaikqM5sH0ziFZCN3xDC7zeGaB/d0IUb9CATugHWbd1FRFwWwt4ld4OYMPWu5a3Xe01mGAULCdqhMlPl29Jg==";
      };
    };
    "@protobufjs/eventemitter-1.1.0" = {
      name = "_at_protobufjs_slash_eventemitter";
      packageName = "@protobufjs/eventemitter";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/eventemitter/-/eventemitter-1.1.0.tgz";
        sha1 = "355cbc98bafad5978f9ed095f397621f1d066b70";
      };
    };
    "@protobufjs/fetch-1.1.0" = {
      name = "_at_protobufjs_slash_fetch";
      packageName = "@protobufjs/fetch";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/fetch/-/fetch-1.1.0.tgz";
        sha1 = "ba99fb598614af65700c1619ff06d454b0d84c45";
      };
    };
    "@protobufjs/float-1.0.2" = {
      name = "_at_protobufjs_slash_float";
      packageName = "@protobufjs/float";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/float/-/float-1.0.2.tgz";
        sha1 = "5e9e1abdcb73fc0a7cb8b291df78c8cbd97b87d1";
      };
    };
    "@protobufjs/inquire-1.1.0" = {
      name = "_at_protobufjs_slash_inquire";
      packageName = "@protobufjs/inquire";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/inquire/-/inquire-1.1.0.tgz";
        sha1 = "ff200e3e7cf2429e2dcafc1140828e8cc638f089";
      };
    };
    "@protobufjs/path-1.1.2" = {
      name = "_at_protobufjs_slash_path";
      packageName = "@protobufjs/path";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/path/-/path-1.1.2.tgz";
        sha1 = "6cc2b20c5c9ad6ad0dccfd21ca7673d8d7fbf68d";
      };
    };
    "@protobufjs/pool-1.1.0" = {
      name = "_at_protobufjs_slash_pool";
      packageName = "@protobufjs/pool";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/pool/-/pool-1.1.0.tgz";
        sha1 = "09fd15f2d6d3abfa9b65bc366506d6ad7846ff54";
      };
    };
    "@protobufjs/utf8-1.1.0" = {
      name = "_at_protobufjs_slash_utf8";
      packageName = "@protobufjs/utf8";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/utf8/-/utf8-1.1.0.tgz";
        sha1 = "a777360b5b39a1a2e5106f8e858f2fd2d060c570";
      };
    };
    "@types/accepts-1.3.5" = {
      name = "_at_types_slash_accepts";
      packageName = "@types/accepts";
      version = "1.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/accepts/-/accepts-1.3.5.tgz";
        sha512 = "jOdnI/3qTpHABjM5cx1Hc0sKsPoYCp+DP/GJRGtDlPd7fiV9oXGGIcjW/ZOxLIvjGz8MA+uMZI9metHlgqbgwQ==";
      };
    };
    "@types/body-parser-1.19.0" = {
      name = "_at_types_slash_body-parser";
      packageName = "@types/body-parser";
      version = "1.19.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/body-parser/-/body-parser-1.19.0.tgz";
        sha512 = "W98JrE0j2K78swW4ukqMleo8R7h/pFETjM2DQ90MF6XK2i4LO4W3gQ71Lt4w3bfm2EvVSyWHplECvB5sK22yFQ==";
      };
    };
    "@types/connect-3.4.35" = {
      name = "_at_types_slash_connect";
      packageName = "@types/connect";
      version = "3.4.35";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/connect/-/connect-3.4.35.tgz";
        sha512 = "cdeYyv4KWoEgpBISTxWvqYsVy444DOqehiF3fM3ne10AmJ62RSyNkUnxMJXHQWRQQX2eR94m5y1IZyDwBjV9FQ==";
      };
    };
    "@types/content-disposition-0.5.4" = {
      name = "_at_types_slash_content-disposition";
      packageName = "@types/content-disposition";
      version = "0.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/content-disposition/-/content-disposition-0.5.4.tgz";
        sha512 = "0mPF08jn9zYI0n0Q/Pnz7C4kThdSt+6LD4amsrYDDpgBfrVWa3TcCOxKX1zkGgYniGagRv8heN2cbh+CAn+uuQ==";
      };
    };
    "@types/cookies-0.7.7" = {
      name = "_at_types_slash_cookies";
      packageName = "@types/cookies";
      version = "0.7.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/cookies/-/cookies-0.7.7.tgz";
        sha512 = "h7BcvPUogWbKCzBR2lY4oqaZbO3jXZksexYJVFvkrFeLgbZjQkU4x8pRq6eg2MHXQhY0McQdqmmsxRWlVAHooA==";
      };
    };
    "@types/cors-2.8.10" = {
      name = "_at_types_slash_cors";
      packageName = "@types/cors";
      version = "2.8.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/cors/-/cors-2.8.10.tgz";
        sha512 = "C7srjHiVG3Ey1nR6d511dtDkCEjxuN9W1HWAEjGq8kpcwmNM6JJkpC0xvabM7BXTG2wDq8Eu33iH9aQKa7IvLQ==";
      };
    };
    "@types/express-4.17.13" = {
      name = "_at_types_slash_express";
      packageName = "@types/express";
      version = "4.17.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/express/-/express-4.17.13.tgz";
        sha512 = "6bSZTPaTIACxn48l50SR+axgrqm6qXFIxrdAKaG6PaJk3+zuUr35hBlgT7vOmJcum+OEaIBLtHV/qloEAFITeA==";
      };
    };
    "@types/express-serve-static-core-4.17.24" = {
      name = "_at_types_slash_express-serve-static-core";
      packageName = "@types/express-serve-static-core";
      version = "4.17.24";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/express-serve-static-core/-/express-serve-static-core-4.17.24.tgz";
        sha512 = "3UJuW+Qxhzwjq3xhwXm2onQcFHn76frIYVbTu+kn24LFxI+dEhdfISDFovPB8VpEgW8oQCTpRuCe+0zJxB7NEA==";
      };
    };
    "@types/fs-capacitor-2.0.0" = {
      name = "_at_types_slash_fs-capacitor";
      packageName = "@types/fs-capacitor";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/fs-capacitor/-/fs-capacitor-2.0.0.tgz";
        sha512 = "FKVPOCFbhCvZxpVAMhdBdTfVfXUpsh15wFHgqOKxh9N9vzWZVuWCSijZ5T4U34XYNnuj2oduh6xcs1i+LPI+BQ==";
      };
    };
    "@types/http-assert-1.5.2" = {
      name = "_at_types_slash_http-assert";
      packageName = "@types/http-assert";
      version = "1.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/http-assert/-/http-assert-1.5.2.tgz";
        sha512 = "Ddzuzv/bB2prZnJKlS1sEYhaeT50wfJjhcTTTQLjEsEZJlk3XB4Xohieyq+P4VXIzg7lrQ1Spd/PfRnBpQsdqA==";
      };
    };
    "@types/http-errors-1.8.1" = {
      name = "_at_types_slash_http-errors";
      packageName = "@types/http-errors";
      version = "1.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/http-errors/-/http-errors-1.8.1.tgz";
        sha512 = "e+2rjEwK6KDaNOm5Aa9wNGgyS9oSZU/4pfSMMPYNOfjvFI0WVXm29+ITRFr6aKDvvKo7uU1jV68MW4ScsfDi7Q==";
      };
    };
    "@types/keygrip-1.0.2" = {
      name = "_at_types_slash_keygrip";
      packageName = "@types/keygrip";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/keygrip/-/keygrip-1.0.2.tgz";
        sha512 = "GJhpTepz2udxGexqos8wgaBx4I/zWIDPh/KOGEwAqtuGDkOUJu5eFvwmdBX4AmB8Odsr+9pHCQqiAqDL/yKMKw==";
      };
    };
    "@types/koa-2.13.4" = {
      name = "_at_types_slash_koa";
      packageName = "@types/koa";
      version = "2.13.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/koa/-/koa-2.13.4.tgz";
        sha512 = "dfHYMfU+z/vKtQB7NUrthdAEiSvnLebvBjwHtfFmpZmB7em2N3WVQdHgnFq+xvyVgxW5jKDmjWfLD3lw4g4uTw==";
      };
    };
    "@types/koa-compose-3.2.5" = {
      name = "_at_types_slash_koa-compose";
      packageName = "@types/koa-compose";
      version = "3.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/koa-compose/-/koa-compose-3.2.5.tgz";
        sha512 = "B8nG/OoE1ORZqCkBVsup/AKcvjdgoHnfi4pZMn5UwAPCbhk/96xyv284eBYW8JlQbQ7zDmnpFr68I/40mFoIBQ==";
      };
    };
    "@types/long-4.0.1" = {
      name = "_at_types_slash_long";
      packageName = "@types/long";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/long/-/long-4.0.1.tgz";
        sha512 = "5tXH6Bx/kNGd3MgffdmP4dy2Z+G4eaXw0SE81Tq3BNadtnMR5/ySMzX4SLEzHJzSmPNn4HIdpQsBvXMUykr58w==";
      };
    };
    "@types/mime-1.3.2" = {
      name = "_at_types_slash_mime";
      packageName = "@types/mime";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/mime/-/mime-1.3.2.tgz";
        sha512 = "YATxVxgRqNH6nHEIsvg6k2Boc1JHI9ZbH5iWFFv/MTkchz3b1ieGDa5T0a9RznNdI0KhVbdbWSN+KWWrQZRxTw==";
      };
    };
    "@types/node-10.17.60" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "10.17.60";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-10.17.60.tgz";
        sha512 = "F0KIgDJfy2nA3zMLmWGKxcH2ZVEtCZXHHdOQs2gSaQ27+lNeEfGxzkIw90aXswATX7AZ33tahPbzy6KAfUreVw==";
      };
    };
    "@types/node-16.7.1" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "16.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-16.7.1.tgz";
        sha512 = "ncRdc45SoYJ2H4eWU9ReDfp3vtFqDYhjOsKlFFUDEn8V1Bgr2RjYal8YT5byfadWIRluhPFU6JiDOl0H6Sl87A==";
      };
    };
    "@types/qs-6.9.7" = {
      name = "_at_types_slash_qs";
      packageName = "@types/qs";
      version = "6.9.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/qs/-/qs-6.9.7.tgz";
        sha512 = "FGa1F62FT09qcrueBA6qYTrJPVDzah9a+493+o2PCXsesWHIn27G98TsSMs3WPNbZIEj4+VJf6saSFpvD+3Zsw==";
      };
    };
    "@types/range-parser-1.2.4" = {
      name = "_at_types_slash_range-parser";
      packageName = "@types/range-parser";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/range-parser/-/range-parser-1.2.4.tgz";
        sha512 = "EEhsLsD6UsDM1yFhAvy0Cjr6VwmpMWqFBCb9w07wVugF7w9nfajxLuVmngTIpgS6svCnm6Vaw+MZhoDCKnOfsw==";
      };
    };
    "@types/serve-static-1.13.10" = {
      name = "_at_types_slash_serve-static";
      packageName = "@types/serve-static";
      version = "1.13.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/serve-static/-/serve-static-1.13.10.tgz";
        sha512 = "nCkHGI4w7ZgAdNkrEu0bv+4xNV/XDqW+DydknebMOQwkpDGx8G+HTlj7R7ABI8i8nKxVw0wtKPi1D+lPOkh4YQ==";
      };
    };
    "@types/ws-7.4.7" = {
      name = "_at_types_slash_ws";
      packageName = "@types/ws";
      version = "7.4.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/ws/-/ws-7.4.7.tgz";
        sha512 = "JQbbmxZTZehdc2iszGKs5oC3NFnjeay7mtAWrdt7qNtAVK0g19muApzAy4bm9byz79xa2ZnO/BOBC2R8RC5Lww==";
      };
    };
    "@types/zen-observable-0.8.3" = {
      name = "_at_types_slash_zen-observable";
      packageName = "@types/zen-observable";
      version = "0.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/zen-observable/-/zen-observable-0.8.3.tgz";
        sha512 = "fbF6oTd4sGGy0xjHPKAt+eS2CrxJ3+6gQ3FGcBoIJR2TLAyCkCyI8JqZNy+FeON0AhVgNJoUumVoZQjBFUqHkw==";
      };
    };
    "@wry/context-0.6.1" = {
      name = "_at_wry_slash_context";
      packageName = "@wry/context";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@wry/context/-/context-0.6.1.tgz";
        sha512 = "LOmVnY1iTU2D8tv4Xf6MVMZZ+juIJ87Kt/plMijjN20NMAXGmH4u8bS1t0uT74cZ5gwpocYueV58YwyI8y+GKw==";
      };
    };
    "@wry/equality-0.1.11" = {
      name = "_at_wry_slash_equality";
      packageName = "@wry/equality";
      version = "0.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@wry/equality/-/equality-0.1.11.tgz";
        sha512 = "mwEVBDUVODlsQQ5dfuLUS5/Tf7jqUKyhKYHmVi4fPB6bDMOfWvUPJmKgS1Z7Za/sOI3vzWt4+O7yCiL/70MogA==";
      };
    };
    "@wry/equality-0.5.2" = {
      name = "_at_wry_slash_equality";
      packageName = "@wry/equality";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@wry/equality/-/equality-0.5.2.tgz";
        sha512 = "oVMxbUXL48EV/C0/M7gLVsoK6qRHPS85x8zECofEZOVvxGmIPLA9o5Z27cc2PoAyZz1S2VoM2A7FLAnpfGlneA==";
      };
    };
    "@wry/trie-0.3.1" = {
      name = "_at_wry_slash_trie";
      packageName = "@wry/trie";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@wry/trie/-/trie-0.3.1.tgz";
        sha512 = "WwB53ikYudh9pIorgxrkHKrQZcCqNM/Q/bDzZBffEaGUKGuHrRb3zZUT9Sh2qw9yogC7SsdRmQ1ER0pqvd3bfw==";
      };
    };
    "accepts-1.3.7" = {
      name = "accepts";
      packageName = "accepts";
      version = "1.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/accepts/-/accepts-1.3.7.tgz";
        sha512 = "Il80Qs2WjYlJIBNzNkK6KYqlVMTbZLXgHx2oT0pU/fjRHyEp+PEfEPY0R3WCwAGVOtauxh1hOxNgIf5bv7dQpA==";
      };
    };
    "apollo-cache-control-0.14.0" = {
      name = "apollo-cache-control";
      packageName = "apollo-cache-control";
      version = "0.14.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/apollo-cache-control/-/apollo-cache-control-0.14.0.tgz";
        sha512 = "qN4BCq90egQrgNnTRMUHikLZZAprf3gbm8rC5Vwmc6ZdLolQ7bFsa769Hqi6Tq/lS31KLsXBLTOsRbfPHph12w==";
      };
    };
    "apollo-datasource-0.9.0" = {
      name = "apollo-datasource";
      packageName = "apollo-datasource";
      version = "0.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/apollo-datasource/-/apollo-datasource-0.9.0.tgz";
        sha512 = "y8H99NExU1Sk4TvcaUxTdzfq2SZo6uSj5dyh75XSQvbpH6gdAXIW9MaBcvlNC7n0cVPsidHmOcHOWxJ/pTXGjA==";
      };
    };
    "apollo-graphql-0.9.3" = {
      name = "apollo-graphql";
      packageName = "apollo-graphql";
      version = "0.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/apollo-graphql/-/apollo-graphql-0.9.3.tgz";
        sha512 = "rcAl2E841Iko4kSzj4Pt3PRBitmyq1MvoEmpl04TQSpGnoVgl1E/ZXuLBYxMTSnEAm7umn2IsoY+c6Ll9U/10A==";
      };
    };
    "apollo-link-1.2.14" = {
      name = "apollo-link";
      packageName = "apollo-link";
      version = "1.2.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/apollo-link/-/apollo-link-1.2.14.tgz";
        sha512 = "p67CMEFP7kOG1JZ0ZkYZwRDa369w5PIjtMjvrQd/HnIV8FRsHRqLqK+oAZQnFa1DDdZtOtHTi+aMIW6EatC2jg==";
      };
    };
    "apollo-reporting-protobuf-0.8.0" = {
      name = "apollo-reporting-protobuf";
      packageName = "apollo-reporting-protobuf";
      version = "0.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/apollo-reporting-protobuf/-/apollo-reporting-protobuf-0.8.0.tgz";
        sha512 = "B3XmnkH6Y458iV6OsA7AhfwvTgeZnFq9nPVjbxmLKnvfkEl8hYADtz724uPa0WeBiD7DSFcnLtqg9yGmCkBohg==";
      };
    };
    "apollo-server-caching-0.7.0" = {
      name = "apollo-server-caching";
      packageName = "apollo-server-caching";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/apollo-server-caching/-/apollo-server-caching-0.7.0.tgz";
        sha512 = "MsVCuf/2FxuTFVhGLK13B+TZH9tBd2qkyoXKKILIiGcZ5CDUEBO14vIV63aNkMkS1xxvK2U4wBcuuNj/VH2Mkw==";
      };
    };
    "apollo-server-core-2.25.2" = {
      name = "apollo-server-core";
      packageName = "apollo-server-core";
      version = "2.25.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/apollo-server-core/-/apollo-server-core-2.25.2.tgz";
        sha512 = "lrohEjde2TmmDTO7FlOs8x5QQbAS0Sd3/t0TaK2TWaodfzi92QAvIsq321Mol6p6oEqmjm8POIDHW1EuJd7XMA==";
      };
    };
    "apollo-server-env-3.1.0" = {
      name = "apollo-server-env";
      packageName = "apollo-server-env";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/apollo-server-env/-/apollo-server-env-3.1.0.tgz";
        sha512 = "iGdZgEOAuVop3vb0F2J3+kaBVi4caMoxefHosxmgzAbbSpvWehB8Y1QiSyyMeouYC38XNVk5wnZl+jdGSsWsIQ==";
      };
    };
    "apollo-server-errors-2.5.0" = {
      name = "apollo-server-errors";
      packageName = "apollo-server-errors";
      version = "2.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/apollo-server-errors/-/apollo-server-errors-2.5.0.tgz";
        sha512 = "lO5oTjgiC3vlVg2RKr3RiXIIQ5pGXBFxYGGUkKDhTud3jMIhs+gel8L8zsEjKaKxkjHhCQAA/bcEfYiKkGQIvA==";
      };
    };
    "apollo-server-express-2.25.2" = {
      name = "apollo-server-express";
      packageName = "apollo-server-express";
      version = "2.25.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/apollo-server-express/-/apollo-server-express-2.25.2.tgz";
        sha512 = "A2gF2e85vvDugPlajbhr0A14cDFDIGX0mteNOJ8P3Z3cIM0D4hwrWxJidI+SzobefDIyIHu1dynFedJVhV0euQ==";
      };
    };
    "apollo-server-plugin-base-0.13.0" = {
      name = "apollo-server-plugin-base";
      packageName = "apollo-server-plugin-base";
      version = "0.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/apollo-server-plugin-base/-/apollo-server-plugin-base-0.13.0.tgz";
        sha512 = "L3TMmq2YE6BU6I4Tmgygmd0W55L+6XfD9137k+cWEBFu50vRY4Re+d+fL5WuPkk5xSPKd/PIaqzidu5V/zz8Kg==";
      };
    };
    "apollo-server-types-0.9.0" = {
      name = "apollo-server-types";
      packageName = "apollo-server-types";
      version = "0.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/apollo-server-types/-/apollo-server-types-0.9.0.tgz";
        sha512 = "qk9tg4Imwpk732JJHBkhW0jzfG0nFsLqK2DY6UhvJf7jLnRePYsPxWfPiNkxni27pLE2tiNlCwoDFSeWqpZyBg==";
      };
    };
    "apollo-tracing-0.15.0" = {
      name = "apollo-tracing";
      packageName = "apollo-tracing";
      version = "0.15.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/apollo-tracing/-/apollo-tracing-0.15.0.tgz";
        sha512 = "UP0fztFvaZPHDhIB/J+qGuy6hWO4If069MGC98qVs0I8FICIGu4/8ykpX3X3K6RtaQ56EDAWKykCxFv4ScxMeA==";
      };
    };
    "apollo-utilities-1.3.4" = {
      name = "apollo-utilities";
      packageName = "apollo-utilities";
      version = "1.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/apollo-utilities/-/apollo-utilities-1.3.4.tgz";
        sha512 = "pk2hiWrCXMAy2fRPwEyhvka+mqwzeP60Jr1tRYi5xru+3ko94HI9o6lK0CT33/w4RDlxWchmdhDCrvdr+pHCig==";
      };
    };
    "array-flatten-1.1.1" = {
      name = "array-flatten";
      packageName = "array-flatten";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-flatten/-/array-flatten-1.1.1.tgz";
        sha1 = "9a5f699051b1e7073328f2a008968b64ea2955d2";
      };
    };
    "async-retry-1.3.3" = {
      name = "async-retry";
      packageName = "async-retry";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/async-retry/-/async-retry-1.3.3.tgz";
        sha512 = "wfr/jstw9xNi/0teMHrRW7dsz3Lt5ARhYNZ2ewpadnhaIp5mbALhOAP+EAdsC7t4Z6wqsDVv9+W6gm1Dk9mEyw==";
      };
    };
    "available-typed-arrays-1.0.4" = {
      name = "available-typed-arrays";
      packageName = "available-typed-arrays";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/available-typed-arrays/-/available-typed-arrays-1.0.4.tgz";
        sha512 = "SA5mXJWrId1TaQjfxUYghbqQ/hYioKmLJvPJyDuYRtXXenFNMjj4hSSt1Cf1xsuXSXrtxrVC5Ot4eU6cOtBDdA==";
      };
    };
    "backo2-1.0.2" = {
      name = "backo2";
      packageName = "backo2";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/backo2/-/backo2-1.0.2.tgz";
        sha1 = "31ab1ac8b129363463e35b3ebb69f4dfcfba7947";
      };
    };
    "bcryptjs-2.4.3" = {
      name = "bcryptjs";
      packageName = "bcryptjs";
      version = "2.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/bcryptjs/-/bcryptjs-2.4.3.tgz";
        sha1 = "9ab5627b93e60621ff7cdac5da9733027df1d0cb";
      };
    };
    "body-parser-1.19.0" = {
      name = "body-parser";
      packageName = "body-parser";
      version = "1.19.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/body-parser/-/body-parser-1.19.0.tgz";
        sha512 = "dhEPs72UPbDnAQJ9ZKMNTP6ptJaionhP5cBb541nXPlW60Jepo9RV/a4fX4XWW9CuFNK22krhrj1+rgzifNCsw==";
      };
    };
    "buffer-equal-constant-time-1.0.1" = {
      name = "buffer-equal-constant-time";
      packageName = "buffer-equal-constant-time";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-equal-constant-time/-/buffer-equal-constant-time-1.0.1.tgz";
        sha1 = "f8e71132f7ffe6e01a5c9697a4c6f3e48d5cc819";
      };
    };
    "busboy-0.3.1" = {
      name = "busboy";
      packageName = "busboy";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/busboy/-/busboy-0.3.1.tgz";
        sha512 = "y7tTxhGKXcyBxRKAni+awqx8uqaJKrSFSNFSeRG5CsWNdmy2BIK+6VGWEW7TZnIO/533mtMEA4rOevQV815YJw==";
      };
    };
    "bytes-3.1.0" = {
      name = "bytes";
      packageName = "bytes";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bytes/-/bytes-3.1.0.tgz";
        sha512 = "zauLjrfCG+xvoyaqLoV8bLVXXNGC4JqlxFCutSDWA6fJrTo2ZuvLYTqZ7aHBLZSMOopbzwv8f+wZcVzfVTI2Dg==";
      };
    };
    "call-bind-1.0.2" = {
      name = "call-bind";
      packageName = "call-bind";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/call-bind/-/call-bind-1.0.2.tgz";
        sha512 = "7O+FbCihrB5WGbFYesctwmTKae6rOiIzmz1icreWJ+0aA7LJfuqhEso2T9ncpcFtzMQtzXf2QGGueWJGTYsqrA==";
      };
    };
    "commander-2.20.3" = {
      name = "commander";
      packageName = "commander";
      version = "2.20.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.20.3.tgz";
        sha512 = "GpVkmM8vF2vQUkj2LvZmD35JxeJOLCwJ9cUkugyk2nuhbv3+mJvpLYYt+0+USMxE+oj+ey/lJEnhZw75x/OMcQ==";
      };
    };
    "content-disposition-0.5.3" = {
      name = "content-disposition";
      packageName = "content-disposition";
      version = "0.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-disposition/-/content-disposition-0.5.3.tgz";
        sha512 = "ExO0774ikEObIAEV9kDo50o+79VCUdEB6n6lzKgGwupcVeRlhrj3qGAfwq8G6uBJjkqLrhT0qEYFcWng8z1z0g==";
      };
    };
    "content-type-1.0.4" = {
      name = "content-type";
      packageName = "content-type";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-type/-/content-type-1.0.4.tgz";
        sha512 = "hIP3EEPs8tB9AT1L+NUqtwOAps4mk2Zob89MWXMHjHWg9milF/j4osnnQLXBCBFBk/tvIG/tUc9mOUJiPBhPXA==";
      };
    };
    "cookie-0.4.0" = {
      name = "cookie";
      packageName = "cookie";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie/-/cookie-0.4.0.tgz";
        sha512 = "+Hp8fLp57wnUSt0tY0tHEXh4voZRDnoIrZPqlo3DPiI4y9lwg/jqx+1Om94/W6ZaPDOUbnjOt/99w66zk+l1Xg==";
      };
    };
    "cookie-parser-1.4.5" = {
      name = "cookie-parser";
      packageName = "cookie-parser";
      version = "1.4.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie-parser/-/cookie-parser-1.4.5.tgz";
        sha512 = "f13bPUj/gG/5mDr+xLmSxxDsB9DQiTIfhJS/sqjrmfAWiAN+x2O4i/XguTL9yDZ+/IFDanJ+5x7hC4CXT9Tdzw==";
      };
    };
    "cookie-signature-1.0.6" = {
      name = "cookie-signature";
      packageName = "cookie-signature";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie-signature/-/cookie-signature-1.0.6.tgz";
        sha1 = "e303a882b342cc3ee8ca513a79999734dab3ae2c";
      };
    };
    "core-js-pure-3.16.2" = {
      name = "core-js-pure";
      packageName = "core-js-pure";
      version = "3.16.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-js-pure/-/core-js-pure-3.16.2.tgz";
        sha512 = "oxKe64UH049mJqrKkynWp6Vu0Rlm/BTXO/bJZuN2mmR3RtOFNepLlSWDd1eo16PzHpQAoNG97rLU1V/YxesJjw==";
      };
    };
    "cors-2.8.5" = {
      name = "cors";
      packageName = "cors";
      version = "2.8.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/cors/-/cors-2.8.5.tgz";
        sha512 = "KIHbLJqu73RGr/hnbrO9uBeixNGuvSQjul/jdFvS/KFSIH1hWVd1ng7zOHx+YrEfInLG7q4n6GHQ9cDtxv/P6g==";
      };
    };
    "cssfilter-0.0.10" = {
      name = "cssfilter";
      packageName = "cssfilter";
      version = "0.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/cssfilter/-/cssfilter-0.0.10.tgz";
        sha1 = "c6d2672632a2e5c83e013e6864a42ce8defd20ae";
      };
    };
    "debug-2.6.9" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz";
        sha512 = "bC7ElrdJaJnPbAP+1EotYvqZsb3ecl5wi6Bfi6BJTUcNowp6cvspg0jXznRTKDjm/E7AdgFBVeAPVMNcKGsHMA==";
      };
    };
    "deep-equal-2.0.5" = {
      name = "deep-equal";
      packageName = "deep-equal";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-equal/-/deep-equal-2.0.5.tgz";
        sha512 = "nPiRgmbAtm1a3JsnLCf6/SLfXcjyN5v8L1TXzdCmHrXJ4hx+gW/w1YCcn7z8gJtSiDArZCgYtbao3QqLm/N1Sw==";
      };
    };
    "define-properties-1.1.3" = {
      name = "define-properties";
      packageName = "define-properties";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-properties/-/define-properties-1.1.3.tgz";
        sha512 = "3MqfYKj2lLzdMSf8ZIZE/V+Zuy+BgD6f164e8K2w7dgnpKArBDerGYpM46IYYcjnkdPNMjPk9A6VFB8+3SKlXQ==";
      };
    };
    "depd-1.1.2" = {
      name = "depd";
      packageName = "depd";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/depd/-/depd-1.1.2.tgz";
        sha1 = "9bcd52e14c097763e749b274c4346ed2e560b5a9";
      };
    };
    "deprecated-decorator-0.1.6" = {
      name = "deprecated-decorator";
      packageName = "deprecated-decorator";
      version = "0.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/deprecated-decorator/-/deprecated-decorator-0.1.6.tgz";
        sha1 = "00966317b7a12fe92f3cc831f7583af329b86c37";
      };
    };
    "destroy-1.0.4" = {
      name = "destroy";
      packageName = "destroy";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/destroy/-/destroy-1.0.4.tgz";
        sha1 = "978857442c44749e4206613e37946205826abd80";
      };
    };
    "dicer-0.3.0" = {
      name = "dicer";
      packageName = "dicer";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dicer/-/dicer-0.3.0.tgz";
        sha512 = "MdceRRWqltEG2dZqO769g27N/3PXfcKl04VhYnBlo2YhH7zPi88VebsjTKclaOyiuMaGU72hTfw3VkUitGcVCA==";
      };
    };
    "dotenv-8.6.0" = {
      name = "dotenv";
      packageName = "dotenv";
      version = "8.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dotenv/-/dotenv-8.6.0.tgz";
        sha512 = "IrPdXQsk2BbzvCBGBOTmmSH5SodmqZNt4ERAZDmW4CT+tL8VtvinqywuANaFu4bOMWki16nqf0e4oC0QIaDr/g==";
      };
    };
    "ecdsa-sig-formatter-1.0.11" = {
      name = "ecdsa-sig-formatter";
      packageName = "ecdsa-sig-formatter";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecdsa-sig-formatter/-/ecdsa-sig-formatter-1.0.11.tgz";
        sha512 = "nagl3RYrbNv6kQkeJIpt6NJZy8twLB/2vtz6yN9Z4vRKHN4/QZJIEbqohALSgwKdnksuY3k5Addp5lg8sVoVcQ==";
      };
    };
    "ee-first-1.1.1" = {
      name = "ee-first";
      packageName = "ee-first";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ee-first/-/ee-first-1.1.1.tgz";
        sha1 = "590c61156b0ae2f4f0255732a158b266bc56b21d";
      };
    };
    "encodeurl-1.0.2" = {
      name = "encodeurl";
      packageName = "encodeurl";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/encodeurl/-/encodeurl-1.0.2.tgz";
        sha1 = "ad3ff4c86ec2d029322f5a02c3a9a606c95b3f59";
      };
    };
    "es-abstract-1.18.5" = {
      name = "es-abstract";
      packageName = "es-abstract";
      version = "1.18.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-abstract/-/es-abstract-1.18.5.tgz";
        sha512 = "DDggyJLoS91CkJjgauM5c0yZMjiD1uK3KcaCeAmffGwZ+ODWzOkPN4QwRbsK5DOFf06fywmyLci3ZD8jLGhVYA==";
      };
    };
    "es-get-iterator-1.1.2" = {
      name = "es-get-iterator";
      packageName = "es-get-iterator";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-get-iterator/-/es-get-iterator-1.1.2.tgz";
        sha512 = "+DTO8GYwbMCwbywjimwZMHp8AuYXOS2JZFWoi2AlPOS3ebnII9w/NLpNZtA7A0YLaVDw+O7KFCeoIV7OPvM7hQ==";
      };
    };
    "es-to-primitive-1.2.1" = {
      name = "es-to-primitive";
      packageName = "es-to-primitive";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-to-primitive/-/es-to-primitive-1.2.1.tgz";
        sha512 = "QCOllgZJtaUo9miYBcLChTUaHNjJF3PYs1VidD7AwiEj1kYxKeQTctLAezAOH5ZKRH0g2IgPn6KwB4IT8iRpvA==";
      };
    };
    "escape-html-1.0.3" = {
      name = "escape-html";
      packageName = "escape-html";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-html/-/escape-html-1.0.3.tgz";
        sha1 = "0258eae4d3d0c0974de1c169188ef0051d1d1988";
      };
    };
    "etag-1.8.1" = {
      name = "etag";
      packageName = "etag";
      version = "1.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/etag/-/etag-1.8.1.tgz";
        sha1 = "41ae2eeb65efa62268aebfea83ac7d79299b0887";
      };
    };
    "eventemitter3-3.1.2" = {
      name = "eventemitter3";
      packageName = "eventemitter3";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/eventemitter3/-/eventemitter3-3.1.2.tgz";
        sha512 = "tvtQIeLVHjDkJYnzf2dgVMxfuSGJeM/7UCG17TT4EumTfNtF+0nebF/4zWOIkCreAbtNqhGEboB6BWrwqNaw4Q==";
      };
    };
    "express-4.17.1" = {
      name = "express";
      packageName = "express";
      version = "4.17.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/express/-/express-4.17.1.tgz";
        sha512 = "mHJ9O79RqluphRrcw2X/GTh3k9tVv8YcoyY4Kkh4WDMUYKRZUq0h1o0w2rrrxBqM7VoeUVqgb27xlEMXTnYt4g==";
      };
    };
    "fast-json-stable-stringify-2.1.0" = {
      name = "fast-json-stable-stringify";
      packageName = "fast-json-stable-stringify";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-json-stable-stringify/-/fast-json-stable-stringify-2.1.0.tgz";
        sha512 = "lhd/wF+Lk98HZoTCtlVraHtfh5XYijIjalXck7saUtuanSDyLMxnHhSXEDJqHxD7msR8D0uCmqlkwjCV8xvwHw==";
      };
    };
    "finalhandler-1.1.2" = {
      name = "finalhandler";
      packageName = "finalhandler";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/finalhandler/-/finalhandler-1.1.2.tgz";
        sha512 = "aAWcW57uxVNrQZqFXjITpW3sIUQmHGG3qSb9mUah9MgMC4NeWhNOlNjXEYq3HjRAvL6arUviZGGJsBg6z0zsWA==";
      };
    };
    "for-each-0.3.3" = {
      name = "for-each";
      packageName = "for-each";
      version = "0.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/for-each/-/for-each-0.3.3.tgz";
        sha512 = "jqYfLp7mo9vIyQf8ykW2v7A+2N4QjeCeI5+Dz9XraiO1ign81wjiH7Fb9vSOWvQfNtmSa4H2RoQTrrXivdUZmw==";
      };
    };
    "foreach-2.0.5" = {
      name = "foreach";
      packageName = "foreach";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/foreach/-/foreach-2.0.5.tgz";
        sha1 = "0bee005018aeb260d0a3af3ae658dd0136ec1b99";
      };
    };
    "forwarded-0.2.0" = {
      name = "forwarded";
      packageName = "forwarded";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/forwarded/-/forwarded-0.2.0.tgz";
        sha512 = "buRG0fpBtRHSTCOASe6hD258tEubFoRLb4ZNA6NxMVHNw2gOcwHo9wyablzMzOA5z9xA9L1KNjk/Nt6MT9aYow==";
      };
    };
    "fresh-0.5.2" = {
      name = "fresh";
      packageName = "fresh";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fresh/-/fresh-0.5.2.tgz";
        sha1 = "3d8cadd90d976569fa835ab1f8e4b23a105605a7";
      };
    };
    "fs-capacitor-2.0.4" = {
      name = "fs-capacitor";
      packageName = "fs-capacitor";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-capacitor/-/fs-capacitor-2.0.4.tgz";
        sha512 = "8S4f4WsCryNw2mJJchi46YgB6CR5Ze+4L1h8ewl9tEpL4SJ3ZO+c/bS4BWhB8bK+O3TMqhuZarTitd0S0eh2pA==";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "get-intrinsic-1.1.1" = {
      name = "get-intrinsic";
      packageName = "get-intrinsic";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-intrinsic/-/get-intrinsic-1.1.1.tgz";
        sha512 = "kWZrnVM42QCiEA2Ig1bG8zjoIMOgxWwYCEeNdwY6Tv/cOSeGpcoX4pXHfKUxNKVoArnrEr2e9srnAxxGIraS9Q==";
      };
    };
    "graphql-15.5.1" = {
      name = "graphql";
      packageName = "graphql";
      version = "15.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/graphql/-/graphql-15.5.1.tgz";
        sha512 = "FeTRX67T3LoE3LWAxxOlW2K3Bz+rMYAC18rRguK4wgXaTZMiJwSUwDmPFo3UadAKbzirKIg5Qy+sNJXbpPRnQw==";
      };
    };
    "graphql-extensions-0.15.0" = {
      name = "graphql-extensions";
      packageName = "graphql-extensions";
      version = "0.15.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/graphql-extensions/-/graphql-extensions-0.15.0.tgz";
        sha512 = "bVddVO8YFJPwuACn+3pgmrEg6I8iBuYLuwvxiE+lcQQ7POotVZxm2rgGw0PvVYmWWf3DT7nTVDZ5ROh/ALp8mA==";
      };
    };
    "graphql-resolvers-0.4.2" = {
      name = "graphql-resolvers";
      packageName = "graphql-resolvers";
      version = "0.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/graphql-resolvers/-/graphql-resolvers-0.4.2.tgz";
        sha512 = "C+BEjS5BrV04I44iNtMDw7ZbmIlSBabkbt5KpF8Vg5wphsm2jDlKklU9DeX/nzs7NEt0tOoorbTmpQH0VyYBLA==";
      };
    };
    "graphql-subscriptions-1.2.1" = {
      name = "graphql-subscriptions";
      packageName = "graphql-subscriptions";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/graphql-subscriptions/-/graphql-subscriptions-1.2.1.tgz";
        sha512 = "95yD/tKi24q8xYa7Q9rhQN16AYj5wPbrb8tmHGM3WRc9EBmWrG/0kkMl+tQG8wcEuE9ibR4zyOM31p5Sdr2v4g==";
      };
    };
    "graphql-tag-2.12.5" = {
      name = "graphql-tag";
      packageName = "graphql-tag";
      version = "2.12.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/graphql-tag/-/graphql-tag-2.12.5.tgz";
        sha512 = "5xNhP4063d16Pz3HBtKprutsPrmHZi5IdUGOWRxA2B6VF7BIRGOHZ5WQvDmJXZuPcBg7rYwaFxvQYjqkSdR3TQ==";
      };
    };
    "graphql-tools-4.0.8" = {
      name = "graphql-tools";
      packageName = "graphql-tools";
      version = "4.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/graphql-tools/-/graphql-tools-4.0.8.tgz";
        sha512 = "MW+ioleBrwhRjalKjYaLQbr+920pHBgy9vM/n47sswtns8+96sRn5M/G+J1eu7IMeKWiN/9p6tmwCHU7552VJg==";
      };
    };
    "graphql-tools-8.2.0" = {
      name = "graphql-tools";
      packageName = "graphql-tools";
      version = "8.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/graphql-tools/-/graphql-tools-8.2.0.tgz";
        sha512 = "9axT/0exEzVCk+vMPykOPannlrA4VQNo6nuWgh25IJ5arPf92OKxvjSHAbm7dQIFmcWxE0hVvyD2rWHjDqZCgQ==";
      };
    };
    "has-1.0.3" = {
      name = "has";
      packageName = "has";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.3.tgz";
        sha512 = "f2dvO0VU6Oej7RkWJGrehjbzMAjFp5/VKPp5tTpWIV4JHHZK1/BxbFRtf/siA2SWTe09caDmVtYYzWEIbBS4zw==";
      };
    };
    "has-bigints-1.0.1" = {
      name = "has-bigints";
      packageName = "has-bigints";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-bigints/-/has-bigints-1.0.1.tgz";
        sha512 = "LSBS2LjbNBTf6287JEbEzvJgftkF5qFkmCo9hDRpAzKhUOlJ+hx8dd4USs00SgsUNwc4617J9ki5YtEClM2ffA==";
      };
    };
    "has-symbols-1.0.2" = {
      name = "has-symbols";
      packageName = "has-symbols";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-symbols/-/has-symbols-1.0.2.tgz";
        sha512 = "chXa79rL/UC2KlX17jo3vRGz0azaWEx5tGqZg5pO3NUyEJVB17dMruQlzCCOfUvElghKcm5194+BCRvi2Rv/Gw==";
      };
    };
    "has-tostringtag-1.0.0" = {
      name = "has-tostringtag";
      packageName = "has-tostringtag";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-tostringtag/-/has-tostringtag-1.0.0.tgz";
        sha512 = "kFjcSNhnlGV1kyoGk7OXKSawH5JOb/LzUc5w9B02hOTO0dfFRjbHQKvg1d6cf3HbeUmtU9VbbV3qzZ2Teh97WQ==";
      };
    };
    "helmet-4.6.0" = {
      name = "helmet";
      packageName = "helmet";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/helmet/-/helmet-4.6.0.tgz";
        sha512 = "HVqALKZlR95ROkrnesdhbbZJFi/rIVSoNq6f3jA/9u6MIbTsPh3xZwihjeI5+DO/2sOV6HMHooXcEOuwskHpTg==";
      };
    };
    "hoist-non-react-statics-3.3.2" = {
      name = "hoist-non-react-statics";
      packageName = "hoist-non-react-statics";
      version = "3.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoist-non-react-statics/-/hoist-non-react-statics-3.3.2.tgz";
        sha512 = "/gGivxi8JPKWNm/W0jSmzcMPpfpPLc3dY/6GxhX2hQ9iGj3aDfklV4ET7NjKpSinLpJ5vafa9iiGIEZg10SfBw==";
      };
    };
    "http-errors-1.7.2" = {
      name = "http-errors";
      packageName = "http-errors";
      version = "1.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-errors/-/http-errors-1.7.2.tgz";
        sha512 = "uUQBt3H/cSIVfch6i1EuPNy/YsRSOUBXTVfZ+yR7Zjez3qjBz6i9+i4zjNaoqcoFVI4lQJ5plg63TvGfRSDCRg==";
      };
    };
    "http-errors-1.7.3" = {
      name = "http-errors";
      packageName = "http-errors";
      version = "1.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-errors/-/http-errors-1.7.3.tgz";
        sha512 = "ZTTX0MWrsQ2ZAhA1cejAwDLycFsd7I7nVtnkT3Ol0aqodaKW+0CTZDQ1uBv5whptCnc8e8HeRRJxRs0kmm/Qfw==";
      };
    };
    "http-errors-1.8.0" = {
      name = "http-errors";
      packageName = "http-errors";
      version = "1.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-errors/-/http-errors-1.8.0.tgz";
        sha512 = "4I8r0C5JDhT5VkvI47QktDW75rNlGVsUf/8hzjCC/wkWI/jdTRmBb9aI7erSG82r1bjKY3F6k28WnsVxB1C73A==";
      };
    };
    "httpntlm-1.6.1" = {
      name = "httpntlm";
      packageName = "httpntlm";
      version = "1.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/httpntlm/-/httpntlm-1.6.1.tgz";
        sha1 = "ad01527143a2e8773cfae6a96f58656bb52a34b2";
      };
    };
    "httpreq-0.5.2" = {
      name = "httpreq";
      packageName = "httpreq";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/httpreq/-/httpreq-0.5.2.tgz";
        sha512 = "2Jm+x9WkExDOeFRrdBCBSpLPT5SokTcRHkunV3pjKmX/cx6av8zQ0WtHUMDrYb6O4hBFzNU6sxJEypvRUVYKnw==";
      };
    };
    "iconv-lite-0.4.24" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.4.24";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.24.tgz";
        sha512 = "v3MXnZAcvnywkTUEZomIActle7RXXeedOR31wwl7VlyoXO4Qi9arvSenNQWne1TcRwhCL1HwLI21bEqdpj8/rA==";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "internal-slot-1.0.3" = {
      name = "internal-slot";
      packageName = "internal-slot";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/internal-slot/-/internal-slot-1.0.3.tgz";
        sha512 = "O0DB1JC/sPyZl7cIo78n5dR7eUSwwpYPiXRhTzNxZVAMUuB8vlnRFyLxdrVToks6XPLVnFfbzaVd5WLjhgg+vA==";
      };
    };
    "ipaddr.js-1.9.1" = {
      name = "ipaddr.js";
      packageName = "ipaddr.js";
      version = "1.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-1.9.1.tgz";
        sha512 = "0KI/607xoxSToH7GjN1FfSbLoU0+btTicjsQSWQlh/hZykN8KpmMf7uYwPW3R+akZ6R/w18ZlXSHBYXiYUPO3g==";
      };
    };
    "is-arguments-1.1.1" = {
      name = "is-arguments";
      packageName = "is-arguments";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-arguments/-/is-arguments-1.1.1.tgz";
        sha512 = "8Q7EARjzEnKpt/PCD7e1cgUS0a6X8u5tdSiMqXhojOdoV9TsMsiO+9VLC5vAmO8N7/GmXn7yjR8qnA6bVAEzfA==";
      };
    };
    "is-bigint-1.0.4" = {
      name = "is-bigint";
      packageName = "is-bigint";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-bigint/-/is-bigint-1.0.4.tgz";
        sha512 = "zB9CruMamjym81i2JZ3UMn54PKGsQzsJeo6xvN3HJJ4CAsQNB6iRutp2To77OfCNuoxspsIhzaPoO1zyCEhFOg==";
      };
    };
    "is-boolean-object-1.1.2" = {
      name = "is-boolean-object";
      packageName = "is-boolean-object";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-boolean-object/-/is-boolean-object-1.1.2.tgz";
        sha512 = "gDYaKHJmnj4aWxyj6YHyXVpdQawtVLHU5cb+eztPGczf6cjuTdwve5ZIEfgXqH4e57An1D1AKf8CZ3kYrQRqYA==";
      };
    };
    "is-callable-1.2.4" = {
      name = "is-callable";
      packageName = "is-callable";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-callable/-/is-callable-1.2.4.tgz";
        sha512 = "nsuwtxZfMX67Oryl9LCQ+upnC0Z0BgpwntpS89m1H/TLF0zNfzfLMV/9Wa/6MZsj0acpEjAO0KF1xT6ZdLl95w==";
      };
    };
    "is-date-object-1.0.5" = {
      name = "is-date-object";
      packageName = "is-date-object";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-date-object/-/is-date-object-1.0.5.tgz";
        sha512 = "9YQaSxsAiSwcvS33MBk3wTCVnWK+HhF8VZR2jRxehM16QcVOdHqPn4VPHmRK4lSr38n9JriurInLcP90xsYNfQ==";
      };
    };
    "is-map-2.0.2" = {
      name = "is-map";
      packageName = "is-map";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-map/-/is-map-2.0.2.tgz";
        sha512 = "cOZFQQozTha1f4MxLFzlgKYPTyj26picdZTx82hbc/Xf4K/tZOOXSCkMvU4pKioRXGDLJRn0GM7Upe7kR721yg==";
      };
    };
    "is-negative-zero-2.0.1" = {
      name = "is-negative-zero";
      packageName = "is-negative-zero";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-negative-zero/-/is-negative-zero-2.0.1.tgz";
        sha512 = "2z6JzQvZRa9A2Y7xC6dQQm4FSTSTNWjKIYYTt4246eMTJmIo0Q+ZyOsU66X8lxK1AbB92dFeglPLrhwpeRKO6w==";
      };
    };
    "is-number-object-1.0.6" = {
      name = "is-number-object";
      packageName = "is-number-object";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number-object/-/is-number-object-1.0.6.tgz";
        sha512 = "bEVOqiRcvo3zO1+G2lVMy+gkkEm9Yh7cDMRusKKu5ZJKPUYSJwICTKZrNKHA2EbSP0Tu0+6B/emsYNHZyn6K8g==";
      };
    };
    "is-regex-1.1.4" = {
      name = "is-regex";
      packageName = "is-regex";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-regex/-/is-regex-1.1.4.tgz";
        sha512 = "kvRdxDsxZjhzUX07ZnLydzS1TU/TJlTUHHY4YLL87e37oUA49DfkLqgy+VjFocowy29cKvcSiu+kIv728jTTVg==";
      };
    };
    "is-set-2.0.2" = {
      name = "is-set";
      packageName = "is-set";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-set/-/is-set-2.0.2.tgz";
        sha512 = "+2cnTEZeY5z/iXGbLhPrOAaK/Mau5k5eXq9j14CpRTftq0pAJu2MwVRSZhyZWBzx3o6X795Lz6Bpb6R0GKf37g==";
      };
    };
    "is-string-1.0.7" = {
      name = "is-string";
      packageName = "is-string";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-string/-/is-string-1.0.7.tgz";
        sha512 = "tE2UXzivje6ofPW7l23cjDOMa09gb7xlAqG6jG5ej6uPV32TlWP3NKPigtaGeHNu9fohccRYvIiZMfOOnOYUtg==";
      };
    };
    "is-symbol-1.0.4" = {
      name = "is-symbol";
      packageName = "is-symbol";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-symbol/-/is-symbol-1.0.4.tgz";
        sha512 = "C/CPBqKWnvdcxqIARxyOh4v1UUEOCHpgDa0WYgpKDFMszcrPcffg5uhwSgPCLD2WWxmq6isisz87tzT01tuGhg==";
      };
    };
    "is-typed-array-1.1.7" = {
      name = "is-typed-array";
      packageName = "is-typed-array";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typed-array/-/is-typed-array-1.1.7.tgz";
        sha512 = "VxlpTBGknhQ3o7YiVjIhdLU6+oD8dPz/79vvvH4F+S/c8608UCVa9fgDpa1kZgFoUST2DCgacc70UszKgzKuvA==";
      };
    };
    "is-weakmap-2.0.1" = {
      name = "is-weakmap";
      packageName = "is-weakmap";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-weakmap/-/is-weakmap-2.0.1.tgz";
        sha512 = "NSBR4kH5oVj1Uwvv970ruUkCV7O1mzgVFO4/rev2cLRda9Tm9HrL70ZPut4rOHgY0FNrUu9BCbXA2sdQ+x0chA==";
      };
    };
    "is-weakset-2.0.1" = {
      name = "is-weakset";
      packageName = "is-weakset";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-weakset/-/is-weakset-2.0.1.tgz";
        sha512 = "pi4vhbhVHGLxohUw7PhGsueT4vRGFoXhP7+RGN0jKIv9+8PWYCQTqtADngrxOm2g46hoH0+g8uZZBzMrvVGDmw==";
      };
    };
    "isarray-2.0.5" = {
      name = "isarray";
      packageName = "isarray";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-2.0.5.tgz";
        sha512 = "xHjhDr3cNBK0BzdUJSPXZntQUx/mwMS5Rw4A7lPJ90XGAO6ISP/ePDNuo0vhqOZU+UD5JoodwCAAoZQd3FeAKw==";
      };
    };
    "iterall-1.3.0" = {
      name = "iterall";
      packageName = "iterall";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/iterall/-/iterall-1.3.0.tgz";
        sha512 = "QZ9qOMdF+QLHxy1QIpUHUU1D5pS2CG2P69LF6L6CPjPYA/XMOmKV3PZpawHoAjHNyB0swdVTRxdYT4tbBbxqwg==";
      };
    };
    "js-tokens-4.0.0" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz";
        sha512 = "RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
      };
    };
    "jsonwebtoken-8.5.1" = {
      name = "jsonwebtoken";
      packageName = "jsonwebtoken";
      version = "8.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonwebtoken/-/jsonwebtoken-8.5.1.tgz";
        sha512 = "XjwVfRS6jTMsqYs0EsuJ4LGxXV14zQybNd4L2r0UvbVnSF9Af8x7p5MzbJ90Ioz/9TI41/hTCvznF/loiSzn8w==";
      };
    };
    "jwa-1.4.1" = {
      name = "jwa";
      packageName = "jwa";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jwa/-/jwa-1.4.1.tgz";
        sha512 = "qiLX/xhEEFKUAJ6FiBMbes3w9ATzyk5W7Hvzpa/SLYdxNtng+gcurvrI7TbACjIXlsJyr05/S1oUhZrc63evQA==";
      };
    };
    "jws-3.2.2" = {
      name = "jws";
      packageName = "jws";
      version = "3.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/jws/-/jws-3.2.2.tgz";
        sha512 = "YHlZCB6lMTllWDtSPHz/ZXTsi8S00usEV6v1tjq8tOUZzw7DpSDWVXjXDre6ed1w/pd495ODpHZYSdkRTsa0HA==";
      };
    };
    "lodash-4.17.21" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz";
        sha512 = "v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==";
      };
    };
    "lodash.includes-4.3.0" = {
      name = "lodash.includes";
      packageName = "lodash.includes";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.includes/-/lodash.includes-4.3.0.tgz";
        sha1 = "60bb98a87cb923c68ca1e51325483314849f553f";
      };
    };
    "lodash.isboolean-3.0.3" = {
      name = "lodash.isboolean";
      packageName = "lodash.isboolean";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isboolean/-/lodash.isboolean-3.0.3.tgz";
        sha1 = "6c2e171db2a257cd96802fd43b01b20d5f5870f6";
      };
    };
    "lodash.isinteger-4.0.4" = {
      name = "lodash.isinteger";
      packageName = "lodash.isinteger";
      version = "4.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isinteger/-/lodash.isinteger-4.0.4.tgz";
        sha1 = "619c0af3d03f8b04c31f5882840b77b11cd68343";
      };
    };
    "lodash.isnumber-3.0.3" = {
      name = "lodash.isnumber";
      packageName = "lodash.isnumber";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isnumber/-/lodash.isnumber-3.0.3.tgz";
        sha1 = "3ce76810c5928d03352301ac287317f11c0b1ffc";
      };
    };
    "lodash.isplainobject-4.0.6" = {
      name = "lodash.isplainobject";
      packageName = "lodash.isplainobject";
      version = "4.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isplainobject/-/lodash.isplainobject-4.0.6.tgz";
        sha1 = "7c526a52d89b45c45cc690b88163be0497f550cb";
      };
    };
    "lodash.isstring-4.0.1" = {
      name = "lodash.isstring";
      packageName = "lodash.isstring";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isstring/-/lodash.isstring-4.0.1.tgz";
        sha1 = "d527dfb5456eca7cc9bb95d5daeaf88ba54a5451";
      };
    };
    "lodash.once-4.1.1" = {
      name = "lodash.once";
      packageName = "lodash.once";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.once/-/lodash.once-4.1.1.tgz";
        sha1 = "0dd3971213c7c56df880977d504c88fb471a97ac";
      };
    };
    "lodash.sortby-4.7.0" = {
      name = "lodash.sortby";
      packageName = "lodash.sortby";
      version = "4.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.sortby/-/lodash.sortby-4.7.0.tgz";
        sha1 = "edd14c824e2cc9c1e0b0a1b42bb5210516a42438";
      };
    };
    "loglevel-1.7.1" = {
      name = "loglevel";
      packageName = "loglevel";
      version = "1.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/loglevel/-/loglevel-1.7.1.tgz";
        sha512 = "Hesni4s5UkWkwCGJMQGAh71PaLUmKFM60dHvq0zi/vDhhrzuk+4GgNbTXJ12YYQJn6ZKBDNIjYcuQGKudvqrIw==";
      };
    };
    "long-4.0.0" = {
      name = "long";
      packageName = "long";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/long/-/long-4.0.0.tgz";
        sha512 = "XsP+KhQif4bjX1kbuSiySJFNAehNxgLb6hPRGJ9QsUr8ajHkuXGdrHmFUTUUXhDwVX2R5bY4JNZEwbUiMhV+MA==";
      };
    };
    "loose-envify-1.4.0" = {
      name = "loose-envify";
      packageName = "loose-envify";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz";
        sha512 = "lyuxPGr/Wfhrlem2CL/UcnUc1zcqKAImBDzukY7Y5F/yQiNdko6+fRLevlw1HgMySw7f611UIY408EtxRSoK3Q==";
      };
    };
    "lru-cache-6.0.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz";
        sha512 = "Jo6dJ04CmSjuznwJSS3pUeWmd/H0ffTlkXXgwZi+eq1UCmqQwCh+eLsYOYCwY991i2Fah4h1BEMCx4qThGbsiA==";
      };
    };
    "media-typer-0.3.0" = {
      name = "media-typer";
      packageName = "media-typer";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/media-typer/-/media-typer-0.3.0.tgz";
        sha1 = "8710d7af0aa626f8fffa1ce00168545263255748";
      };
    };
    "merge-descriptors-1.0.1" = {
      name = "merge-descriptors";
      packageName = "merge-descriptors";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge-descriptors/-/merge-descriptors-1.0.1.tgz";
        sha1 = "b00aaa556dd8b44568150ec9d1b953f3f90cbb61";
      };
    };
    "methods-1.1.2" = {
      name = "methods";
      packageName = "methods";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/methods/-/methods-1.1.2.tgz";
        sha1 = "5529a4d67654134edcc5266656835b0f851afcee";
      };
    };
    "mime-1.6.0" = {
      name = "mime";
      packageName = "mime";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.6.0.tgz";
        sha512 = "x0Vn8spI+wuJ1O6S7gnbaQg8Pxh4NNHb7KSINmEWKiPE4RKOplvijn+NkmYmmRgP68mc70j2EbeTFRsrswaQeg==";
      };
    };
    "mime-db-1.49.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.49.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.49.0.tgz";
        sha512 = "CIc8j9URtOVApSFCQIF+VBkX1RwXp/oMMOrqdyXSBXq5RWNEsRfyj1kiRnQgmNXmHxPoFIxOroKA3zcU9P+nAA==";
      };
    };
    "mime-types-2.1.32" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.32";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.32.tgz";
        sha512 = "hJGaVS4G4c9TSMYh2n6SQAGrC4RnfU+daP8G7cSCmaqNjiOoUY0VHCMS42pxnQmVF1GWwFhbHWn3RIxCqTmZ9A==";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha1 = "5608aeadfc00be6c2901df5f9861788de0d597c8";
      };
    };
    "ms-2.1.1" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.1.tgz";
        sha512 = "tgp+dl5cGk28utYktBsrFqA7HKgrhgPsg6Z/EfhWI4gl1Hwq8B/GmY/0oXZ6nF8hDVesS/FpnYaD/kOWhYQvyg==";
      };
    };
    "ms-2.1.3" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.3.tgz";
        sha512 = "6FlzubTLZG3J2a/NVCAleEhjzq5oxgHyaCU9yYXvcLsvoVaHJq/s5xXI6/XXP6tz7R9xAOtHnSO/tXtF3WRTlA==";
      };
    };
    "negotiator-0.6.2" = {
      name = "negotiator";
      packageName = "negotiator";
      version = "0.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/negotiator/-/negotiator-0.6.2.tgz";
        sha512 = "hZXc7K2e+PgeI1eDBe/10Ard4ekbfrrqG8Ep+8Jmf4JID2bNg7NvCPOZN+kfF574pFQI7mum2AUqDidoKqcTOw==";
      };
    };
    "node-fetch-2.6.1" = {
      name = "node-fetch";
      packageName = "node-fetch";
      version = "2.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch/-/node-fetch-2.6.1.tgz";
        sha512 = "V4aYg89jEoVRxRb2fJdAg8FHvI7cEyYdVAh94HH0UIK8oJxUfkjlDQN9RbMx+bEjP7+ggMiFRprSti032Oipxw==";
      };
    };
    "nodemailer-6.6.3" = {
      name = "nodemailer";
      packageName = "nodemailer";
      version = "6.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/nodemailer/-/nodemailer-6.6.3.tgz";
        sha512 = "faZFufgTMrphYoDjvyVpbpJcYzwyFnbAMmQtj1lVBYAUSm3SOy2fIdd9+Mr4UxPosBa0JRw9bJoIwQn+nswiew==";
      };
    };
    "nodemailer-fetch-1.6.0" = {
      name = "nodemailer-fetch";
      packageName = "nodemailer-fetch";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nodemailer-fetch/-/nodemailer-fetch-1.6.0.tgz";
        sha1 = "79c4908a1c0f5f375b73fe888da9828f6dc963a4";
      };
    };
    "nodemailer-shared-1.1.0" = {
      name = "nodemailer-shared";
      packageName = "nodemailer-shared";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nodemailer-shared/-/nodemailer-shared-1.1.0.tgz";
        sha1 = "cf5994e2fd268d00f5cf0fa767a08169edb07ec0";
      };
    };
    "nodemailer-smtp-transport-2.7.4" = {
      name = "nodemailer-smtp-transport";
      packageName = "nodemailer-smtp-transport";
      version = "2.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/nodemailer-smtp-transport/-/nodemailer-smtp-transport-2.7.4.tgz";
        sha1 = "0d89af019a144a480fd8ecc99997d9f838f13685";
      };
    };
    "nodemailer-wellknown-0.1.10" = {
      name = "nodemailer-wellknown";
      packageName = "nodemailer-wellknown";
      version = "0.1.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/nodemailer-wellknown/-/nodemailer-wellknown-0.1.10.tgz";
        sha1 = "586db8101db30cb4438eb546737a41aad0cf13d5";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "object-inspect-1.11.0" = {
      name = "object-inspect";
      packageName = "object-inspect";
      version = "1.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-inspect/-/object-inspect-1.11.0.tgz";
        sha512 = "jp7ikS6Sd3GxQfZJPyH3cjcbJF6GZPClgdV+EFygjFLQ5FmW/dRUnTd9PQ9k0JhoNDabWFbpF1yCdSWCC6gexg==";
      };
    };
    "object-is-1.1.5" = {
      name = "object-is";
      packageName = "object-is";
      version = "1.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-is/-/object-is-1.1.5.tgz";
        sha512 = "3cyDsyHgtmi7I7DfSSI2LDp6SK2lwvtbg0p0R1e0RvTqF5ceGx+K2dfSjm1bKDMVCFEDAQvy+o8c6a7VujOddw==";
      };
    };
    "object-keys-1.1.1" = {
      name = "object-keys";
      packageName = "object-keys";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-keys/-/object-keys-1.1.1.tgz";
        sha512 = "NuAESUOUMrlIXOfHKzD6bpPu3tYt3xvjNdRIQ+FeT0lNb4K8WR70CaDxhuNguS2XG+GjkyMwOzsN5ZktImfhLA==";
      };
    };
    "object-path-0.11.8" = {
      name = "object-path";
      packageName = "object-path";
      version = "0.11.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-path/-/object-path-0.11.8.tgz";
        sha512 = "YJjNZrlXJFM42wTBn6zgOJVar9KFJvzx6sTWDte8sWZF//cnjl0BxHNpfZx+ZffXX63A9q0b1zsFiBX4g4X5KA==";
      };
    };
    "object.assign-4.1.2" = {
      name = "object.assign";
      packageName = "object.assign";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.assign/-/object.assign-4.1.2.tgz";
        sha512 = "ixT2L5THXsApyiUPYKmW+2EHpXXe5Ii3M+f4e+aJFAHao5amFRW6J0OO6c/LU8Be47utCx2GL89hxGB6XSmKuQ==";
      };
    };
    "object.getownpropertydescriptors-2.1.2" = {
      name = "object.getownpropertydescriptors";
      packageName = "object.getownpropertydescriptors";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.getownpropertydescriptors/-/object.getownpropertydescriptors-2.1.2.tgz";
        sha512 = "WtxeKSzfBjlzL+F9b7M7hewDzMwy+C8NRssHd1YrNlzHzIDrXcXiNOMrezdAEM4UXixgV+vvnyBeN7Rygl2ttQ==";
      };
    };
    "on-finished-2.3.0" = {
      name = "on-finished";
      packageName = "on-finished";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/on-finished/-/on-finished-2.3.0.tgz";
        sha1 = "20f1336481b083cd75337992a16971aa2d906947";
      };
    };
    "optimism-0.16.1" = {
      name = "optimism";
      packageName = "optimism";
      version = "0.16.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/optimism/-/optimism-0.16.1.tgz";
        sha512 = "64i+Uw3otrndfq5kaoGNoY7pvOhSsjFEN4bdEFh80MWVk/dbgJfMv7VFDeCT8LxNAlEVhQmdVEbfE7X2nWNIIg==";
      };
    };
    "parseurl-1.3.3" = {
      name = "parseurl";
      packageName = "parseurl";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/parseurl/-/parseurl-1.3.3.tgz";
        sha512 = "CiyeOxFT/JZyN5m0z9PfXw4SCBJ6Sygz1Dpl0wqjlhDEGGBP1GnsUVEL0p63hoG1fcj3fHynXi9NYO4nWOL+qQ==";
      };
    };
    "path-to-regexp-0.1.7" = {
      name = "path-to-regexp";
      packageName = "path-to-regexp";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-to-regexp/-/path-to-regexp-0.1.7.tgz";
        sha1 = "df604178005f522f15eb4490e7247a1bfaa67f8c";
      };
    };
    "prop-types-15.7.2" = {
      name = "prop-types";
      packageName = "prop-types";
      version = "15.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prop-types/-/prop-types-15.7.2.tgz";
        sha512 = "8QQikdH7//R2vurIJSutZ1smHYTcLpRWEOlHnzcWHmBYrOGUysKwSsrC89BCiFj3CbrfJ/nXFdJepOVrY1GCHQ==";
      };
    };
    "proxy-addr-2.0.7" = {
      name = "proxy-addr";
      packageName = "proxy-addr";
      version = "2.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/proxy-addr/-/proxy-addr-2.0.7.tgz";
        sha512 = "llQsMLSUDUPT44jdrU/O37qlnifitDP+ZwrmmZcoSKyLKvtZxpyV0n2/bD/N4tBAAZ/gJEdZU7KMraoK1+XYAg==";
      };
    };
    "qs-6.7.0" = {
      name = "qs";
      packageName = "qs";
      version = "6.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.7.0.tgz";
        sha512 = "VCdBRNFTX1fyE7Nb6FYoURo/SPe62QCaAyzJvUjwRaIsc+NePBEniHlvxFmmX56+HZphIGtV0XeCirBtpDrTyQ==";
      };
    };
    "range-parser-1.2.1" = {
      name = "range-parser";
      packageName = "range-parser";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/range-parser/-/range-parser-1.2.1.tgz";
        sha512 = "Hrgsx+orqoygnmhFbKaHE6c296J+HTAQXoxEF6gNupROmmGJRoyzfG3ccAveqCBrwr/2yxQ5BVd/GTl5agOwSg==";
      };
    };
    "raw-body-2.4.0" = {
      name = "raw-body";
      packageName = "raw-body";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/raw-body/-/raw-body-2.4.0.tgz";
        sha512 = "4Oz8DUIwdvoa5qMJelxipzi/iJIi40O5cGV1wNYp5hvZP8ZN0T+jiNkL0QepXs+EsQ9XJ8ipEDoiH70ySUJP3Q==";
      };
    };
    "react-is-16.13.1" = {
      name = "react-is";
      packageName = "react-is";
      version = "16.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-is/-/react-is-16.13.1.tgz";
        sha512 = "24e6ynE2H+OKt4kqsOvNd8kBpV65zoxbA4BVsEOB3ARVWQki/DHzaUoC5KuON/BiccDaCCTZBuOcfZs70kR8bQ==";
      };
    };
    "regenerator-runtime-0.13.9" = {
      name = "regenerator-runtime";
      packageName = "regenerator-runtime";
      version = "0.13.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.13.9.tgz";
        sha512 = "p3VT+cOEgxFsRRA9X4lkI1E+k2/CtnKtU4gcxyaCUreilL/vqI6CdZ3wxVUx3UOUg+gnUOQQcRI7BmSI656MYA==";
      };
    };
    "regexp.prototype.flags-1.3.1" = {
      name = "regexp.prototype.flags";
      packageName = "regexp.prototype.flags";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/regexp.prototype.flags/-/regexp.prototype.flags-1.3.1.tgz";
        sha512 = "JiBdRBq91WlY7uRJ0ds7R+dU02i6LKi8r3BuQhNXn+kmeLN+EfHhfjqMRis1zJxnlu88hq/4dx0P2OP3APRTOA==";
      };
    };
    "retry-0.13.1" = {
      name = "retry";
      packageName = "retry";
      version = "0.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/retry/-/retry-0.13.1.tgz";
        sha512 = "XQBQ3I8W1Cge0Seh+6gjj03LbmRFWuoszgK9ooCpwYIrhhoO80pfq4cUkU5DkknwfOfFteRwlZ56PYOGYyFWdg==";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "semver-5.7.1" = {
      name = "semver";
      packageName = "semver";
      version = "5.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.7.1.tgz";
        sha512 = "sauaDf/PZdVgrLTNYHRtpXa1iRiKcaebiKQ1BJdpQlWH2lCvexQdX55snPFyK7QzpudqbCI0qXFfOasHdyNDGQ==";
      };
    };
    "send-0.17.1" = {
      name = "send";
      packageName = "send";
      version = "0.17.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/send/-/send-0.17.1.tgz";
        sha512 = "BsVKsiGcQMFwT8UxypobUKyv7irCNRHk1T0G680vk88yf6LBByGcZJOTJCrTP2xVN6yI+XjPJcNuE3V4fT9sAg==";
      };
    };
    "serve-static-1.14.1" = {
      name = "serve-static";
      packageName = "serve-static";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/serve-static/-/serve-static-1.14.1.tgz";
        sha512 = "JMrvUwE54emCYWlTI+hGrGv5I8dEwmco/00EvkzIIsR7MqrHonbD9pO2MOfFnpFntl7ecpZs+3mW+XbQZu9QCg==";
      };
    };
    "setprototypeof-1.1.1" = {
      name = "setprototypeof";
      packageName = "setprototypeof";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/setprototypeof/-/setprototypeof-1.1.1.tgz";
        sha512 = "JvdAWfbXeIGaZ9cILp38HntZSFSo3mWg6xGcJJsd+d4aRMOqauag1C63dJfDw7OaMYwEbHMOxEZ1lqVRYP2OAw==";
      };
    };
    "setprototypeof-1.2.0" = {
      name = "setprototypeof";
      packageName = "setprototypeof";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/setprototypeof/-/setprototypeof-1.2.0.tgz";
        sha512 = "E5LDX7Wrp85Kil5bhZv46j8jOeboKq5JMmYM3gVGdGH8xFpPWXUMsNrlODCrkoxMEeNi/XZIwuRvY4XNwYMJpw==";
      };
    };
    "sha.js-2.4.11" = {
      name = "sha.js";
      packageName = "sha.js";
      version = "2.4.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/sha.js/-/sha.js-2.4.11.tgz";
        sha512 = "QMEp5B7cftE7APOjk5Y6xgrbWu+WkLVQwk8JNjZ8nKRciZaByEW6MubieAiToS7+dwvrjGhH8jRXz3MVd0AYqQ==";
      };
    };
    "side-channel-1.0.4" = {
      name = "side-channel";
      packageName = "side-channel";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/side-channel/-/side-channel-1.0.4.tgz";
        sha512 = "q5XPytqFEIKHkGdiMIrY10mvLRvnQh42/+GoBlFW3b2LXLE2xxJpZFdm94we0BaoV3RwJyGqg5wS7epxTv0Zvw==";
      };
    };
    "smtp-connection-2.12.0" = {
      name = "smtp-connection";
      packageName = "smtp-connection";
      version = "2.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/smtp-connection/-/smtp-connection-2.12.0.tgz";
        sha1 = "d76ef9127cb23c2259edb1e8349c2e8d5e2d74c1";
      };
    };
    "statuses-1.5.0" = {
      name = "statuses";
      packageName = "statuses";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/statuses/-/statuses-1.5.0.tgz";
        sha1 = "161c7dac177659fd9811f43771fa99381478628c";
      };
    };
    "streamsearch-0.1.2" = {
      name = "streamsearch";
      packageName = "streamsearch";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/streamsearch/-/streamsearch-0.1.2.tgz";
        sha1 = "808b9d0e56fc273d809ba57338e929919a1a9f1a";
      };
    };
    "string.prototype.trimend-1.0.4" = {
      name = "string.prototype.trimend";
      packageName = "string.prototype.trimend";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.trimend/-/string.prototype.trimend-1.0.4.tgz";
        sha512 = "y9xCjw1P23Awk8EvTpcyL2NIr1j7wJ39f+k6lvRnSMz+mz9CGz9NYPelDk42kOz6+ql8xjfK8oYzy3jAP5QU5A==";
      };
    };
    "string.prototype.trimstart-1.0.4" = {
      name = "string.prototype.trimstart";
      packageName = "string.prototype.trimstart";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.trimstart/-/string.prototype.trimstart-1.0.4.tgz";
        sha512 = "jh6e984OBfvxS50tdY2nRZnoC5/mLFKOREQfw8t5yytkoUsJRNxvI/E39qu1sD0OtWI3OC0XgKSmcWwziwYuZw==";
      };
    };
    "subscriptions-transport-ws-0.9.19" = {
      name = "subscriptions-transport-ws";
      packageName = "subscriptions-transport-ws";
      version = "0.9.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/subscriptions-transport-ws/-/subscriptions-transport-ws-0.9.19.tgz";
        sha512 = "dxdemxFFB0ppCLg10FTtRqH/31FNRL1y1BQv8209MK5I4CwALb7iihQg+7p65lFcIl8MHatINWBLOqpgU4Kyyw==";
      };
    };
    "symbol-observable-1.2.0" = {
      name = "symbol-observable";
      packageName = "symbol-observable";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/symbol-observable/-/symbol-observable-1.2.0.tgz";
        sha512 = "e900nM8RRtGhlV36KGEU9k65K3mPb1WV70OdjfxlG2EAuM1noi/E/BaW/uMhL7bPEssK8QV57vN3esixjUvcXQ==";
      };
    };
    "symbol-observable-4.0.0" = {
      name = "symbol-observable";
      packageName = "symbol-observable";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/symbol-observable/-/symbol-observable-4.0.0.tgz";
        sha512 = "b19dMThMV4HVFynSAM1++gBHAbk2Tc/osgLIBZMKsyqh34jb2e8Os7T6ZW/Bt3pJFdBTd2JwAnAAEQV7rSNvcQ==";
      };
    };
    "toidentifier-1.0.0" = {
      name = "toidentifier";
      packageName = "toidentifier";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/toidentifier/-/toidentifier-1.0.0.tgz";
        sha512 = "yaOH/Pk/VEhBWWTlhI+qXxDFXlejDGcQipMlyxda9nthulaxLZUNcUqFxokp0vcYnvteJln5FNQDRrxj3YcbVw==";
      };
    };
    "ts-invariant-0.4.4" = {
      name = "ts-invariant";
      packageName = "ts-invariant";
      version = "0.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/ts-invariant/-/ts-invariant-0.4.4.tgz";
        sha512 = "uEtWkFM/sdZvRNNDL3Ehu4WVpwaulhwQszV8mrtcdeE8nN00BV9mAmQ88RkrBhFgl9gMgvjJLAQcZbnPXI9mlA==";
      };
    };
    "ts-invariant-0.9.3" = {
      name = "ts-invariant";
      packageName = "ts-invariant";
      version = "0.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ts-invariant/-/ts-invariant-0.9.3.tgz";
        sha512 = "HinBlTbFslQI0OHP07JLsSXPibSegec6r9ai5xxq/qHYCsIQbzpymLpDhAUsnXcSrDEcd0L62L8vsOEdzM0qlA==";
      };
    };
    "tslib-1.14.1" = {
      name = "tslib";
      packageName = "tslib";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-1.14.1.tgz";
        sha512 = "Xni35NKzjgMrwevysHTCArtLDpPvye8zV/0E4EyYn43P7/7qvQwPh9BGkHewbMulVntbigmcT7rdX3BNo9wRJg==";
      };
    };
    "tslib-2.3.1" = {
      name = "tslib";
      packageName = "tslib";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-2.3.1.tgz";
        sha512 = "77EbyPPpMz+FRFRuAFlWMtmgUWGe9UOG2Z25NqCwiIjRhOf5iKGuzSe5P2w1laq+FkRy4p+PCuVkJSGkzTEKVw==";
      };
    };
    "type-is-1.6.18" = {
      name = "type-is";
      packageName = "type-is";
      version = "1.6.18";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-is/-/type-is-1.6.18.tgz";
        sha512 = "TkRKr9sUTxEH8MdfuCSP7VizJyzRNMjj2J2do2Jr3Kym598JVdEksuzPQCnlFPW4ky9Q+iA+ma9BGm06XQBy8g==";
      };
    };
    "unbox-primitive-1.0.1" = {
      name = "unbox-primitive";
      packageName = "unbox-primitive";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/unbox-primitive/-/unbox-primitive-1.0.1.tgz";
        sha512 = "tZU/3NqK3dA5gpE1KtyiJUrEB0lxnGkMFHptJ7q6ewdZ8s12QrODwNbhIJStmJkd1QDXa1NRA8aF2A1zk/Ypyw==";
      };
    };
    "underscore-1.7.0" = {
      name = "underscore";
      packageName = "underscore";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore/-/underscore-1.7.0.tgz";
        sha1 = "6bbaf0877500d36be34ecaa584e0db9fef035209";
      };
    };
    "unpipe-1.0.0" = {
      name = "unpipe";
      packageName = "unpipe";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unpipe/-/unpipe-1.0.0.tgz";
        sha1 = "b2bf4ee8514aae6165b4817829d21b2ef49904ec";
      };
    };
    "util.promisify-1.1.1" = {
      name = "util.promisify";
      packageName = "util.promisify";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/util.promisify/-/util.promisify-1.1.1.tgz";
        sha512 = "/s3UsZUrIfa6xDhr7zZhnE9SLQ5RIXyYfiVnMMyMDzOc8WhWN4Nbh36H842OyurKbCDAesZOJaVyvmSl6fhGQw==";
      };
    };
    "utils-merge-1.0.1" = {
      name = "utils-merge";
      packageName = "utils-merge";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/utils-merge/-/utils-merge-1.0.1.tgz";
        sha1 = "9f95710f50a267947b2ccc124741c1028427e713";
      };
    };
    "uuid-3.4.0" = {
      name = "uuid";
      packageName = "uuid";
      version = "3.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-3.4.0.tgz";
        sha512 = "HjSDRw6gZE5JMggctHBcjVak08+KEVhSIiDzFnT9S9aegmp85S/bReBVTb4QTFaRNptJ9kuYaNhnbNEOkbKb/A==";
      };
    };
    "uuid-8.3.2" = {
      name = "uuid";
      packageName = "uuid";
      version = "8.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-8.3.2.tgz";
        sha512 = "+NYs2QeMWy+GWFOEm9xnn6HCDp0l7QBD7ml8zLUmJ+93Q5NF0NocErnwkTkXVFNiX3/fpC6afS8Dhb/gz7R7eg==";
      };
    };
    "value-or-promise-1.0.10" = {
      name = "value-or-promise";
      packageName = "value-or-promise";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/value-or-promise/-/value-or-promise-1.0.10.tgz";
        sha512 = "1OwTzvcfXkAfabk60UVr5NdjtjJ0Fg0T5+B1bhxtrOEwSH2fe8y4DnLgoksfCyd8yZCOQQHB0qLMQnwgCjbXLQ==";
      };
    };
    "vary-1.1.2" = {
      name = "vary";
      packageName = "vary";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vary/-/vary-1.1.2.tgz";
        sha1 = "2299f02c6ded30d4a5961b0b9f74524a18f634fc";
      };
    };
    "which-boxed-primitive-1.0.2" = {
      name = "which-boxed-primitive";
      packageName = "which-boxed-primitive";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/which-boxed-primitive/-/which-boxed-primitive-1.0.2.tgz";
        sha512 = "bwZdv0AKLpplFY2KZRX6TvyuN7ojjr7lwkg6ml0roIy9YeuSr7JS372qlNW18UQYzgYK9ziGcerWqZOmEn9VNg==";
      };
    };
    "which-collection-1.0.1" = {
      name = "which-collection";
      packageName = "which-collection";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/which-collection/-/which-collection-1.0.1.tgz";
        sha512 = "W8xeTUwaln8i3K/cY1nGXzdnVZlidBcagyNFtBdD5kxnb4TvGKR7FfSIS3mYpwWS1QUCutfKz8IY8RjftB0+1A==";
      };
    };
    "which-typed-array-1.1.6" = {
      name = "which-typed-array";
      packageName = "which-typed-array";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/which-typed-array/-/which-typed-array-1.1.6.tgz";
        sha512 = "DdY984dGD5sQ7Tf+x1CkXzdg85b9uEel6nr4UkFg1LoE9OXv3uRuZhe5CoWdawhGACeFpEZXH8fFLQnDhbpm/Q==";
      };
    };
    "ws-7.5.3" = {
      name = "ws";
      packageName = "ws";
      version = "7.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-7.5.3.tgz";
        sha512 = "kQ/dHIzuLrS6Je9+uv81ueZomEwH0qVYstcAQ4/Z93K8zeko9gtAbttJWzoC5ukqXY1PpoouV3+VSOqEAFt5wg==";
      };
    };
    "xss-1.0.9" = {
      name = "xss";
      packageName = "xss";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/xss/-/xss-1.0.9.tgz";
        sha512 = "2t7FahYnGJys6DpHLhajusId7R0Pm2yTmuL0GV9+mV0ZlaLSnb2toBmppATfg5sWIhZQGlsTLoecSzya+l4EAQ==";
      };
    };
    "yallist-4.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
        sha512 = "3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
      };
    };
    "zen-observable-0.8.15" = {
      name = "zen-observable";
      packageName = "zen-observable";
      version = "0.8.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/zen-observable/-/zen-observable-0.8.15.tgz";
        sha512 = "PQ2PC7R9rslx84ndNBZB/Dkv8V8fZEpk83RLgXtYd0fwUgEjseMn1Dgajh2x6S8QbZAFa9p2qVCEuYZNgve0dQ==";
      };
    };
    "zen-observable-ts-0.8.21" = {
      name = "zen-observable-ts";
      packageName = "zen-observable-ts";
      version = "0.8.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/zen-observable-ts/-/zen-observable-ts-0.8.21.tgz";
        sha512 = "Yj3yXweRc8LdRMrCC8nIc4kkjWecPAUVh0TI0OUrWXx6aX790vLcDlWca6I4vsyCGH3LpWxq0dJRcMOFoVqmeg==";
      };
    };
    "zen-observable-ts-1.1.0" = {
      name = "zen-observable-ts";
      packageName = "zen-observable-ts";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/zen-observable-ts/-/zen-observable-ts-1.1.0.tgz";
        sha512 = "1h4zlLSqI2cRLPJUHJFL8bCWHhkpuXkF+dbGkRaWjgDIG26DmzyshUMrdV/rL3UnR+mhaX4fRq8LPouq0MYYIA==";
      };
    };
  };
  args = {
    name = "internbackend";
    packageName = "internbackend";
    version = "1.0.0";
    src = ./..;
    dependencies = [
      (sources."@apollo/client-3.4.11" // {
        dependencies = [
          sources."@wry/equality-0.5.2"
          sources."symbol-observable-4.0.0"
          sources."ts-invariant-0.9.3"
          sources."zen-observable-ts-1.1.0"
        ];
      })
      (sources."@apollo/protobufjs-1.2.2" // {
        dependencies = [
          sources."@types/node-10.17.60"
        ];
      })
      sources."@apollographql/apollo-tools-0.5.1"
      sources."@apollographql/graphql-playground-html-1.6.27"
      sources."@apollographql/graphql-upload-8-fork-8.1.3"
      sources."@babel/runtime-7.15.3"
      sources."@graphql-tools/merge-8.1.2"
      sources."@graphql-tools/schema-8.2.0"
      sources."@graphql-tools/utils-8.2.2"
      sources."@graphql-typed-document-node/core-3.1.0"
      sources."@josephg/resolvable-1.0.1"
      sources."@prisma/client-3.2.0"
      sources."@prisma/engines-version-3.2.0-34.afdab2f10860244038c4e32458134112852d4dad"
      sources."@protobufjs/aspromise-1.1.2"
      sources."@protobufjs/base64-1.1.2"
      sources."@protobufjs/codegen-2.0.4"
      sources."@protobufjs/eventemitter-1.1.0"
      sources."@protobufjs/fetch-1.1.0"
      sources."@protobufjs/float-1.0.2"
      sources."@protobufjs/inquire-1.1.0"
      sources."@protobufjs/path-1.1.2"
      sources."@protobufjs/pool-1.1.0"
      sources."@protobufjs/utf8-1.1.0"
      sources."@types/accepts-1.3.5"
      sources."@types/body-parser-1.19.0"
      sources."@types/connect-3.4.35"
      sources."@types/content-disposition-0.5.4"
      sources."@types/cookies-0.7.7"
      sources."@types/cors-2.8.10"
      sources."@types/express-4.17.13"
      sources."@types/express-serve-static-core-4.17.24"
      sources."@types/fs-capacitor-2.0.0"
      sources."@types/http-assert-1.5.2"
      sources."@types/http-errors-1.8.1"
      sources."@types/keygrip-1.0.2"
      sources."@types/koa-2.13.4"
      sources."@types/koa-compose-3.2.5"
      sources."@types/long-4.0.1"
      sources."@types/mime-1.3.2"
      sources."@types/node-16.7.1"
      sources."@types/qs-6.9.7"
      sources."@types/range-parser-1.2.4"
      sources."@types/serve-static-1.13.10"
      sources."@types/ws-7.4.7"
      sources."@types/zen-observable-0.8.3"
      sources."@wry/context-0.6.1"
      (sources."@wry/equality-0.1.11" // {
        dependencies = [
          sources."tslib-1.14.1"
        ];
      })
      sources."@wry/trie-0.3.1"
      sources."accepts-1.3.7"
      sources."apollo-cache-control-0.14.0"
      sources."apollo-datasource-0.9.0"
      sources."apollo-graphql-0.9.3"
      (sources."apollo-link-1.2.14" // {
        dependencies = [
          sources."tslib-1.14.1"
        ];
      })
      sources."apollo-reporting-protobuf-0.8.0"
      sources."apollo-server-caching-0.7.0"
      (sources."apollo-server-core-2.25.2" // {
        dependencies = [
          (sources."graphql-tools-4.0.8" // {
            dependencies = [
              sources."uuid-3.4.0"
            ];
          })
        ];
      })
      sources."apollo-server-env-3.1.0"
      sources."apollo-server-errors-2.5.0"
      (sources."apollo-server-express-2.25.2" // {
        dependencies = [
          sources."graphql-tools-4.0.8"
          sources."uuid-3.4.0"
        ];
      })
      sources."apollo-server-plugin-base-0.13.0"
      sources."apollo-server-types-0.9.0"
      sources."apollo-tracing-0.15.0"
      (sources."apollo-utilities-1.3.4" // {
        dependencies = [
          sources."tslib-1.14.1"
        ];
      })
      sources."array-flatten-1.1.1"
      sources."async-retry-1.3.3"
      sources."available-typed-arrays-1.0.4"
      sources."backo2-1.0.2"
      sources."bcryptjs-2.4.3"
      (sources."body-parser-1.19.0" // {
        dependencies = [
          sources."http-errors-1.7.2"
          sources."inherits-2.0.3"
          sources."setprototypeof-1.1.1"
        ];
      })
      sources."buffer-equal-constant-time-1.0.1"
      sources."busboy-0.3.1"
      sources."bytes-3.1.0"
      sources."call-bind-1.0.2"
      sources."commander-2.20.3"
      (sources."content-disposition-0.5.3" // {
        dependencies = [
          sources."safe-buffer-5.1.2"
        ];
      })
      sources."content-type-1.0.4"
      sources."cookie-0.4.0"
      sources."cookie-parser-1.4.5"
      sources."cookie-signature-1.0.6"
      sources."core-js-pure-3.16.2"
      sources."cors-2.8.5"
      sources."cssfilter-0.0.10"
      sources."debug-2.6.9"
      sources."deep-equal-2.0.5"
      sources."define-properties-1.1.3"
      sources."depd-1.1.2"
      sources."deprecated-decorator-0.1.6"
      sources."destroy-1.0.4"
      sources."dicer-0.3.0"
      sources."dotenv-8.6.0"
      sources."ecdsa-sig-formatter-1.0.11"
      sources."ee-first-1.1.1"
      sources."encodeurl-1.0.2"
      sources."es-abstract-1.18.5"
      sources."es-get-iterator-1.1.2"
      sources."es-to-primitive-1.2.1"
      sources."escape-html-1.0.3"
      sources."etag-1.8.1"
      sources."eventemitter3-3.1.2"
      (sources."express-4.17.1" // {
        dependencies = [
          sources."safe-buffer-5.1.2"
          sources."setprototypeof-1.1.1"
        ];
      })
      sources."fast-json-stable-stringify-2.1.0"
      sources."finalhandler-1.1.2"
      sources."for-each-0.3.3"
      sources."foreach-2.0.5"
      sources."forwarded-0.2.0"
      sources."fresh-0.5.2"
      sources."fs-capacitor-2.0.4"
      sources."function-bind-1.1.1"
      sources."get-intrinsic-1.1.1"
      sources."graphql-15.5.1"
      sources."graphql-extensions-0.15.0"
      sources."graphql-resolvers-0.4.2"
      sources."graphql-subscriptions-1.2.1"
      sources."graphql-tag-2.12.5"
      sources."graphql-tools-8.2.0"
      sources."has-1.0.3"
      sources."has-bigints-1.0.1"
      sources."has-symbols-1.0.2"
      sources."has-tostringtag-1.0.0"
      sources."helmet-4.6.0"
      sources."hoist-non-react-statics-3.3.2"
      sources."http-errors-1.8.0"
      sources."httpntlm-1.6.1"
      sources."httpreq-0.5.2"
      sources."iconv-lite-0.4.24"
      sources."inherits-2.0.4"
      sources."internal-slot-1.0.3"
      sources."ipaddr.js-1.9.1"
      sources."is-arguments-1.1.1"
      sources."is-bigint-1.0.4"
      sources."is-boolean-object-1.1.2"
      sources."is-callable-1.2.4"
      sources."is-date-object-1.0.5"
      sources."is-map-2.0.2"
      sources."is-negative-zero-2.0.1"
      sources."is-number-object-1.0.6"
      sources."is-regex-1.1.4"
      sources."is-set-2.0.2"
      sources."is-string-1.0.7"
      sources."is-symbol-1.0.4"
      sources."is-typed-array-1.1.7"
      sources."is-weakmap-2.0.1"
      sources."is-weakset-2.0.1"
      sources."isarray-2.0.5"
      sources."iterall-1.3.0"
      sources."js-tokens-4.0.0"
      (sources."jsonwebtoken-8.5.1" // {
        dependencies = [
          sources."ms-2.1.3"
          sources."semver-5.7.1"
        ];
      })
      sources."jwa-1.4.1"
      sources."jws-3.2.2"
      sources."lodash-4.17.21"
      sources."lodash.includes-4.3.0"
      sources."lodash.isboolean-3.0.3"
      sources."lodash.isinteger-4.0.4"
      sources."lodash.isnumber-3.0.3"
      sources."lodash.isplainobject-4.0.6"
      sources."lodash.isstring-4.0.1"
      sources."lodash.once-4.1.1"
      sources."lodash.sortby-4.7.0"
      sources."loglevel-1.7.1"
      sources."long-4.0.0"
      sources."loose-envify-1.4.0"
      sources."lru-cache-6.0.0"
      sources."media-typer-0.3.0"
      sources."merge-descriptors-1.0.1"
      sources."methods-1.1.2"
      sources."mime-1.6.0"
      sources."mime-db-1.49.0"
      sources."mime-types-2.1.32"
      sources."ms-2.0.0"
      sources."negotiator-0.6.2"
      sources."node-fetch-2.6.1"
      sources."nodemailer-6.6.3"
      sources."nodemailer-fetch-1.6.0"
      sources."nodemailer-shared-1.1.0"
      sources."nodemailer-smtp-transport-2.7.4"
      sources."nodemailer-wellknown-0.1.10"
      sources."object-assign-4.1.1"
      sources."object-inspect-1.11.0"
      sources."object-is-1.1.5"
      sources."object-keys-1.1.1"
      sources."object-path-0.11.8"
      sources."object.assign-4.1.2"
      sources."object.getownpropertydescriptors-2.1.2"
      sources."on-finished-2.3.0"
      sources."optimism-0.16.1"
      sources."parseurl-1.3.3"
      sources."path-to-regexp-0.1.7"
      sources."prop-types-15.7.2"
      sources."proxy-addr-2.0.7"
      sources."qs-6.7.0"
      sources."range-parser-1.2.1"
      (sources."raw-body-2.4.0" // {
        dependencies = [
          sources."http-errors-1.7.2"
          sources."inherits-2.0.3"
          sources."setprototypeof-1.1.1"
        ];
      })
      sources."react-is-16.13.1"
      sources."regenerator-runtime-0.13.9"
      sources."regexp.prototype.flags-1.3.1"
      sources."retry-0.13.1"
      sources."safe-buffer-5.2.1"
      sources."safer-buffer-2.1.2"
      (sources."send-0.17.1" // {
        dependencies = [
          sources."http-errors-1.7.3"
          sources."ms-2.1.1"
          sources."setprototypeof-1.1.1"
        ];
      })
      sources."serve-static-1.14.1"
      sources."setprototypeof-1.2.0"
      sources."sha.js-2.4.11"
      sources."side-channel-1.0.4"
      sources."smtp-connection-2.12.0"
      sources."statuses-1.5.0"
      sources."streamsearch-0.1.2"
      sources."string.prototype.trimend-1.0.4"
      sources."string.prototype.trimstart-1.0.4"
      sources."subscriptions-transport-ws-0.9.19"
      sources."symbol-observable-1.2.0"
      sources."toidentifier-1.0.0"
      (sources."ts-invariant-0.4.4" // {
        dependencies = [
          sources."tslib-1.14.1"
        ];
      })
      sources."tslib-2.3.1"
      sources."type-is-1.6.18"
      sources."unbox-primitive-1.0.1"
      sources."underscore-1.7.0"
      sources."unpipe-1.0.0"
      sources."util.promisify-1.1.1"
      sources."utils-merge-1.0.1"
      sources."uuid-8.3.2"
      sources."value-or-promise-1.0.10"
      sources."vary-1.1.2"
      sources."which-boxed-primitive-1.0.2"
      sources."which-collection-1.0.1"
      sources."which-typed-array-1.1.6"
      sources."ws-7.5.3"
      sources."xss-1.0.9"
      sources."yallist-4.0.0"
      sources."zen-observable-0.8.15"
      (sources."zen-observable-ts-0.8.21" // {
        dependencies = [
          sources."tslib-1.14.1"
        ];
      })
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Internside Backend";
      license = "ISC";
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
